pairs:
  - symbol: "KRW-ETH"
    base_timeframe: "60m"
    target_timeframes:
      - "60m"
  - symbol: "KRW-PEPE"
    token_address: "0x6982508145454Ce325dDbE47a25d4ec3d2311933"
    base_timeframe: "60m"
    target_timeframes:
      - "60m"
  - symbol: "KRW-LINK"
    token_address: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
    base_timeframe: "60m"
    target_timeframes:
      - "60m"
  - symbol: "KRW-UNI"
    token_address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"
    base_timeframe: "60m"
    target_timeframes:
      - "60m"
  - symbol: "KRW-SHIB"
    token_address: "0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE"
    base_timeframe: "60m"
    target_timeframes:
      - "60m"
  - symbol: "KRW-USDT"
    token_address: "0xdac17f958d2ee523a2206206994597c13d831ec7"
    base_timeframe: "60m"
    target_timeframes:
      - "60m"
